/*
 * File: app/view/CurrentPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Halovision.view.CurrentPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.CurrentPanel',

    config: {
        title: 'Halovision',
        id: 'CurrentPanel',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'chart',
                id: 'AccelerometerChart',
                animate: false,
                store: 'AccelerometerStore',
                axes: [
                    {
                        type: 'category',
                        fields: [
                            'id'
                        ]
                    },
                    {
                        type: 'numeric',
                        fields: [
                            'x'
                        ],
                        grid: {
                            odd: {
                                fill: '#e8e8e8'
                            }
                        },
                        position: 'left'
                    }
                ],
                series: [
                    {
                        type: 'line',
                        style: {
                            stroke: 'rgb(75, 147, 241)',
                            lineWidth: 2
                        },
                        xField: 'id',
                        yField: 'x'
                    }
                ],
                interactions: [
                    {
                        type: 'panzoom'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    pack: 'justify',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        id: 'WatchButton',
                        itemId: 'mybutton',
                        iconCls: 'time',
                        text: 'Monitor'
                    },
                    {
                        xtype: 'button',
                        id: 'SettingsButton',
                        iconCls: 'settings',
                        text: 'Settings'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onWatchButtonTap',
                event: 'tap',
                delegate: '#WatchButton'
            },
            {
                fn: 'onSettingsButtonTap',
                event: 'tap',
                delegate: '#SettingsButton'
            }
        ]
    },

    onWatchButtonTap: function(button, e, eOpts) {
        Halovision.app.getController("MainController").Watch();
    },

    onSettingsButtonTap: function(button, e, eOpts) {
        Halovision.app.getController("MainController").ShowSettings();
    }

});